steps:
  # 1. Build the Frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/frontend-app:$COMMIT_SHA', '.']

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/frontend-app:$COMMIT_SHA']

  # 3. Deploy to Cloud Run with environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/frontend-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,GOOGLE_CLIENT_EMAIL=google-client-email:latest,GOOGLE_PRIVATE_KEY=google-private-key:latest'
      - '--set-env-vars'
      - 'ARCHIVE_URL=https://archive-service-491839702672.us-central1.run.app'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/frontend-app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
